# Use an official Python runtime as a parent image
FROM python:3.9

# Update the package index and install necessary dependencies
RUN apt-get update && \
    apt-get install -y sshpass

# Install Ansible using pip
RUN pip install --upgrade pip && \
    pip install ansible

# Set the working directory for the container
WORKDIR /ansible

# Show the Ansible version as the default command
CMD [ "ansible", "--version" ]
